app:
  config:
    data-file:
      datetime-format: 'dd-MM-yyyy HH:mm:ss'
      input:
        touch-file-path: src/main/resources/datafiles/input/touchData.csv
      output:
        parent-path: src/main/resources/datafiles/output/
        trips-file-name: trips.csv
        summary-file-name: tripSummary.csv
        unprocessable-file-name: unprocessableTouchData.csv

spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:local}
  datasource:
    driver.class: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:db}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  h2.console:
    enabled: true
    path: /console/